server:
  port: 8083
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profiles:
      active: native
  data:
      mongodb:
        uri: mongodb://admin:admin@localhost:27017/produto?authSource=admin&retryWrites=true&w=majority
        database: venda
        auto-index-creation: true

application:
  produtoService:
    url: http://localhost:8082
    endpointConsultarProduto: http://localhost:8082/produto
  clienteService:
    url: http://localhost:8081
    endpointConsultarCliente: http://localhost:8081/cliente/isCadastrado/{id}